#!/usr/bin/env sh
# vim: ft=sh ts=2 sw=2 st=2
cat <<-help

            _  __ _ __
            / |/ //// /
          / || // U / 
          /_/|_/ \_,'  

    Node Virtual Environments

help
echo  "> \033[32msource nu\033[0m && echo \"Have Fine.\"\n"
